# Generated by Django 5.0.1 on 2024-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Card Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Cash Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Debt Amount'),
        ),
    ]
