# Generated by Django 5.0.1 on 2024-02-20 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_price_remove_product_in_stock_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Delivered Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='needed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Needed Amount'),
        ),
    ]
