# Generated by Django 5.0.1 on 2024-02-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_warehouse_orderitem_comment_orderitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Comment'),
        ),
    ]
