# Generated by Django 5.0.1 on 2024-02-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_payment_comment'),
        ('stores', '0003_product_productunit_alter_warehouseproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.product', verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
