# Generated by Django 5.0.1 on 2024-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_product_unit_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remain_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Remain Debt'),
        ),
    ]
