# Generated by Django 5.0.1 on 2024-02-21 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_remain_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.CreateModel(
            name='DebtPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Amount')),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_paybacks', to='orders.orderitem', verbose_name='Order Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_paybacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Debt Payback',
                'verbose_name_plural': 'Debt Paybacks',
            },
        ),
    ]
