# Generated by Django 5.0.1 on 2024-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtpayback',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Card amount'),
        ),
        migrations.AlterField(
            model_name='debtpayback',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Cash amount'),
        ),
    ]
