# Generated by Django 5.0.1 on 2024-03-28 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_debtpayback_card_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='main_stockman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_stockman_orders', to=settings.AUTH_USER_MODEL, verbose_name='Main stockman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='watchman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchman_orders', to=settings.AUTH_USER_MODEL, verbose_name='Watchman'),
        ),
    ]
