# Generated by Django 5.0.1 on 2024-01-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='delivered_quantity',
            new_name='delivered_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='needed_quantity',
            new_name='needed_amount',
        ),
    ]
