# Generated by Django 5.0.1 on 2024-01-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_delivered_quantity_orderitem_delivered_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delivered Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='needed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Needed Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.productunit', verbose_name='Unit'),
        ),
    ]
