# Generated by Django 5.0.1 on 2024-01-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_orderitem_delivered_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('final_checked', 'Final checked'), ('canceled', 'Canceled')], default='created', max_length=31, verbose_name='Status'),
        ),
    ]
