# Generated by Django 5.0.1 on 2024-01-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('main_stockman', 'Main Stockman'), ('stockman', 'Stockman'), ('supplier', 'Supplier'), ('watchman', 'Watchman')], default='admin', max_length=20),
        ),
    ]
