# Generated by Django 5.0.1 on 2024-02-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quantity'),
        ),
    ]
